version: '3.9'

services:
  db-init:
    image: postgres:15
    volumes:
      - ./blockscout-db-data:/mnt/sdb/blockscout/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /mnt/sdb/blockscout/postgresql/data

  db1:
    image: postgres:15
    user: 2000:2000
    shm_size: 256m
    restart: always
    container_name: 'db1'
    command: postgres -c 'max_connections=200' -c 'client_connection_check_interval=60000'
    environment:
        POSTGRES_DB: 'blockscout'
        POSTGRES_USER: 'blockscout'
        POSTGRES_PASSWORD: 'ceWb1MeLBEeOIfk65gU8EjF8'
    ports:
      - target: 5432
        published: 7434
    volumes:
      - ./blockscout-db-data:/mnt/sdb/blockscout/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
